
services:
  db:  # Сервис БД
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my-postgres
    ports:
      - "8088:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:  # Только ОДИН блок app!
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=my-postgres;Username=root;Password=password
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: